In [1]:
# 데이터 읽기
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [2]:
# 데이터 분리(분할)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=1, stratify=iris.target)
# train_test_split의 iris.data는 분할시킬 x(꽃잎 길이 등)&y(붓꽃 종류)데이터,
# test_size : 학습 데이터셋의 비율이나 갯수
# random_state : 데이터 분할 시 셔플이 이루어지는데 이를 위한 시드값(셔플은 기본적으로 True)
# Stratify : 지정한 데이터의 비율을 유지. 
# 예를 들어, Label Set인 Y가 25%의 0과 75%의 1로 이루어진 Binary Set일 때, stratify=Y로 설정하면 나누어진 데이터셋들도 0과 1을 각각 25%, 75%로 유지한 채 분할된다.

In [3]:
# 데이터 갯수 확인
import numpy as np
print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

(array([0, 1, 2]), array([35, 35, 35]))
(array([0, 1, 2]), array([15, 15, 15]))


In [5]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
x_train_sd = sc.transform(X_train)
x_test_sd = sc.transform(X_test)

In [7]:
x_train_sd

array([[-0.4301064 ,  2.63118533, -1.33269725, -1.30728421],
       [-0.55053619,  0.76918392, -1.16537974, -1.30728421],
       [ 0.65376173,  0.30368356,  0.84243039,  1.44587881],
       [ 1.0150511 ,  0.53643374,  1.0655204 ,  1.18367281],
       [-1.03225536,  0.30368356, -1.44424226, -1.30728421],
       [ 1.0150511 ,  0.07093339,  1.0097479 ,  1.57698181],
       [ 2.09891923, -0.16181679,  1.56747294,  1.18367281],
       [-0.06881702,  2.16568498, -1.44424226, -1.30728421],
       [ 1.61720006, -0.16181679,  1.12129291,  0.5281578 ],
       [ 0.89462131, -0.39456697,  0.45202286,  0.1348488 ],
       [-1.03225536, -1.79106803, -0.27301968, -0.2584602 ],
       [-0.79139578, -0.86006732,  0.06161534,  0.2659518 ],
       [-1.39354474,  0.30368356, -1.38846976, -1.30728421],
       [ 0.29247235, -0.62731714,  0.50779537,  0.0037458 ],
       [-0.4301064 , -1.32556767,  0.11738784,  0.1348488 ],
       [-0.06881702, -0.86006732,  0.73088538,  0.92146681],
       [-1.27311494,  0.

In [8]:
# 모델 생성
from sklearn.linear_model import Perceptron

clf = Perceptron(max_iter = 100, eta0 = 0.1, random_state=13, n_iter_no_change = 10)
clf.fit(x_train_sd, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
           fit_intercept=True, max_iter=100, n_iter_no_change=10, n_jobs=None,
           penalty=None, random_state=13, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [11]:
# 학습 결과
from sklearn.metrics import accuracy_score,confusion_matrix

print("Train Accuracy : ", accuracy_score(y_train, clf.predict(x_train_sd)))
print("Test Accuracy : ", accuracy_score(y_test, clf.predict(x_test_sd)))
print("Train Confusion Matrix : ", confusion_matrix(y_train, clf.predict(x_train_sd)))
print("Test Confusion Matrix : ", confusion_matrix(y_test, clf.predict(x_test_sd)))

Train Accuracy :  0.9619047619047619
Test Accuracy :  0.9777777777777777
Train Confusion Matrix :  [[35  0  0]
 [ 0 33  2]
 [ 0  2 33]]
Test Confusion Matrix :  [[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


## 로지스틱 회귀를 이용한 iris 분류

In [12]:
# 데이터 읽기
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()

In [29]:
# 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.3, random_state = 1, 
                                                   stratify = iris.target)

In [30]:
# 데이터 갯수 확인
import numpy as np
print(np.unique(y_train, return_counts = True))
print(np.unique(y_test, return_counts = True))

(array([0, 1, 2]), array([35, 35, 35]))
(array([0, 1, 2]), array([15, 15, 15]))


In [31]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
x_train_sd = sc.transform(X_train)
x_test_sd = sc.transform(X_test)

In [32]:
# 로지스틱 회귀 모델 생성
from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(solver = 'liblinear', multi_class = 'auto', C = 10.0, random_state = 13)
clf_lr.fit(x_train_sd, y_train)

LogisticRegression(C=10.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=13, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
# 클래스별 확률 값 출력
clf_lr.predict_proba(x_test_sd[0].reshape(1,-1))

array([[5.33348043e-04, 8.98457442e-02, 9.09620908e-01]])

In [35]:
# 학습 결과
from sklearn.metrics import accuracy_score,confusion_matrix

print("Train Accuracy : ", accuracy_score(y_train, clf_lr.predict(x_train_sd)))
print("Test Accuracy : ", accuracy_score(y_test, clf_lr.predict(x_test_sd)))
print("Train Confusion Matrix : ", confusion_matrix(y_train, clf_lr.predict(x_train_sd)))
print("Test Confusion Matrix : ", confusion_matrix(y_test, clf_lr.predict(x_test_sd)))

Train Accuracy :  0.9428571428571428
Test Accuracy :  0.9777777777777777
Train Confusion Matrix :  [[35  0  0]
 [ 0 32  3]
 [ 0  3 32]]
Test Confusion Matrix :  [[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


## Support Vector Machine을 이용한 iris 분류

In [36]:
# 데이터 읽기
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()

In [37]:
# 데이터 분리
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, 
                                                    test_size=0.3, stratify=iris.target)

In [39]:
# 데이터 갯수 확인
import numpy as np
print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

(array([0, 1, 2]), array([35, 35, 35]))
(array([0, 1, 2]), array([15, 15, 15]))


In [40]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
x_train_sd = sc.transform(X_train)
x_test_sd = sc.transform(X_test)

In [41]:
# 모델 생성
from sklearn.svm import SVC

clf_svm = SVC(kernel='linear', random_state=13, C=1.0)
clf_svm.fit(x_train_sd, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=13,
    shrinking=True, tol=0.001, verbose=False)

In [42]:
# 학습 결과
from sklearn.metrics import accuracy_score, confusion_matrix

print("Train Accuracy : ", accuracy_score(y_train, clf_svm.predict(x_train_sd)))
print("Test Accruacy : ", accuracy_score(y_test, clf_svm.predict(x_test_sd)))
print("Train Confusion Matrix : ", confusion_matrix(y_train, clf_svm.predict(x_train_sd)))
print("Test Confusion Matrix : ", confusion_matrix(y_test, clf_svm.predict(x_test_sd)))

Train Accuracy :  0.9809523809523809
Test Accruacy :  0.9555555555555556
Train Confusion Matrix :  [[35  0  0]
 [ 0 34  1]
 [ 0  1 34]]
Test Confusion Matrix :  [[15  0  0]
 [ 0 13  2]
 [ 0  0 15]]


## K-NN을 이용한 iris 분류

In [43]:
# 데이터 읽기
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()

In [45]:
# 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                   test_size=0.3, random_state=1, stratify=iris.target)

In [48]:
# 데이터 갯수 확인
import numpy as np
print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

(array([0, 1, 2]), array([35, 35, 35]))
(array([0, 1, 2]), array([15, 15, 15]))


In [50]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
x_train_sd = sc.transform(X_train)
x_test_sd = sc.transform(X_test)

In [52]:
# 모델 생성
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, p=2)
knn.fit(x_train_sd, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [53]:
# 학습 결과
from sklearn.metrics import accuracy_score, confusion_matrix

print("Train Accuracy:", accuracy_score(y_train, knn.predict(x_train_sd)))
print("Test Accuracy:", accuracy_score(y_test, knn.predict(x_test_sd)))
print("Train Confusion Matrix:", confusion_matrix(y_train, knn.predict(x_train_sd)))
print("Test Confusion Matrix:", confusion_matrix(y_test, knn.predict(x_test_sd)))

Train Accuracy: 0.9619047619047619
Test Accuracy: 0.9333333333333333
Train Confusion Matrix: [[35  0  0]
 [ 0 33  2]
 [ 0  2 33]]
Test Confusion Matrix: [[15  0  0]
 [ 0 13  2]
 [ 0  1 14]]
